[workspace]
members = ["crates/*", "test-playground"]
exclude = [
    "crates/hodu_cuda_kernels",
    "crates/hodu_metal_kernels",
    "plugins/hodu-compiler-cpu",
    "plugins/hodu-compiler-metal",
    "plugins/hodu-runtime-cpu",
    "plugins/hodu-runtime-metal"
]
resolver = "2"

[package]
name = "hodu"
version = "0.2.4"
description = "A user-friendly ML framework built in Rust for rapid prototyping and embedded deployment"
license = "BSD-3-Clause"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/hodu-rs/hodu"
documentation = "https://docs.rs/hodu"
readme = "README.md"
keywords = ["tensor", "machine-learning", "hodu"]
categories = ["science"]

[[bin]]
name = "hodu"
path = "src/cli.rs"
required-features = ["cli"]

[features]
cli = [
    "std",
    "serde",
    "dep:clap",
    "dep:hodu_core",
    "dep:hodu_plugin",

    "hodu_core/json",

    "f8e5m2",
    "f64",
    "u16",
    "u64",
    "i16",
    "i64",

    "hodu_plugin/f8e5m2",
    "hodu_plugin/f64",
    "hodu_plugin/u16",
    "hodu_plugin/u64",
    "hodu_plugin/i16",
    "hodu_plugin/i64",

    "hodu_core/f8e5m2",
    "hodu_core/f64",
    "hodu_core/u16",
    "hodu_core/u64",
    "hodu_core/i16",
    "hodu_core/i64",
]

default = ["std", "serde"]
std = ["hodu_internal/std"]
serde = ["hodu_internal/serde"]

f8e5m2 = ["hodu_internal/f8e5m2"]
f64 = ["hodu_internal/f64"]
u16 = ["hodu_internal/u16"]
u64 = ["hodu_internal/u64"]
i16 = ["hodu_internal/i16"]
i64 = ["hodu_internal/i64"]

openblas = ["hodu_internal/openblas"]

cuda = ["hodu_internal/cuda"]
metal = ["std", "hodu_internal/metal"]

xla = ["std", "hodu_internal/xla"]

[dependencies]
clap = { version = "4.5.53", features = ["derive"], optional = true }
hodu_core = { workspace = true, optional = true }
hodu_internal = { workspace = true }
hodu_plugin = { workspace = true, optional = true }

[workspace.dependencies]
dashmap = "6.1.0"
float8 = { version = "0.4.2", default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
half = { version = "2.7.1", default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
hodu_compat = { path = "crates/hodu_compat", version = "0.2.4" }
hodu_core = { path = "crates/hodu_core", version = "0.2.4" }
hodu_cpu_kernels = { path = "crates/hodu_cpu_kernels", version = "0.2.4" }
hodu_cuda_kernels = { path = "crates/hodu_cuda_kernels", version = "0.2.4" }
hodu_internal = { path = "crates/hodu_internal", version = "0.2.4" }
hodu_macro_utils = { path = "crates/hodu_macro_utils", version = "0.2.4" }
hodu_metal_kernels = { path = "crates/hodu_metal_kernels", version = "0.2.4" }
hodu_nn = { path = "crates/hodu_nn", version = "0.2.4" }
hodu_nn_macros = { path = "crates/hodu_nn/macros", version = "0.2.4" }
hodu_utils = { path = "crates/hodu_utils", version = "0.2.4" }
hodu_utils_macros = { path = "crates/hodu_utils/macros", version = "0.2.4" }
hodu_plugin = { path = "crates/hodu_plugin", version = "0.2.4" }
hodu_xla = "0.4.7"
libloading = "0.9.0"
num-traits = { version = "0.2.19", default-features = false }
paste = "1.0.15"
postcard = { version = "1.1.3", default-features = false, features = ["alloc"] }
proc-macro2 = "1.0"
quote = "1.0"
rand = { version = "0.9.2", default-features = false }
rand_distr = { version = "0.5.1", default-features = false }
serde = { version = "1.0.228", default-features = false, features = [
    "derive",
    "alloc",
] }
serde_json = { version = "1.0.145", default-features = false, features = ["alloc"] }
serde_repr = "0.1.20"
smallvec = { version = "1.15.1" }
spin = "0.10"
syn = { version = "2.0", features = ["full"] }
toml_edit = { version = "0.23.6", default-features = false, features = [
    "parse",
] }
