[workspace]
members = ["crates/*", "hodu-cli", "hodu-lib"]
exclude = ["benchmarks", "crates/hodu_cuda_kernels", "crates/hodu_metal_kernels"]
resolver = "2"

[workspace.dependencies]
bincode = "2.0.1"
dashmap = "6.1.0"
flate2 = "1.1.2"
float8 = { version = "0.4.2", default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
half = { version = "2.7.1", default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
hodu_compat = { path = "crates/hodu_compat", version = "0.2.4" }
hodu_core = { path = "crates/hodu_core", version = "0.2.4" }
hodu_cpu_kernels = { path = "crates/hodu_cpu_kernels", version = "0.2.4" }
hodu_cuda_kernels = { path = "crates/hodu_cuda_kernels", version = "0.2.4" }
hodu_internal = { path = "crates/hodu_internal", version = "0.2.4" }
hodu_macro_utils = { path = "crates/hodu_macro_utils", version = "0.2.4" }
hodu_metal_kernels = { path = "crates/hodu_metal_kernels", version = "0.2.4" }
hodu_nn = { path = "crates/hodu_nn", version = "0.2.4" }
hodu_nn_macros = { path = "crates/hodu_nn/macros", version = "0.2.4" }
hodu_utils = { path = "crates/hodu_utils", version = "0.2.4" }
hodu_utils_macros = { path = "crates/hodu_utils/macros", version = "0.2.4" }
hodu_xla = "0.4.7"
num-traits = { version = "0.2.19", default-features = false }
paste = "1.0.15"
proc-macro2 = "1.0"
quote = "1.0"
rand = { version = "0.9.2", default-features = false }
rand_distr = { version = "0.5.1", default-features = false }
rayon = "1.11"
serde = { version = "1.0.219", default-features = false, features = [
    "derive",
    "alloc",
] }
smallvec = { version = "1.15.1" }
spin = "0.10"
syn = { version = "2.0", features = ["full"] }
toml_edit = { version = "0.23.6", default-features = false, features = [
    "parse",
] }
