[workspace]
members = ["crates/*", "benchmarks/*"]
exclude = ["benchmarks/.venvs", "crates/hodu_cuda_kernels", "crates/hodu_metal_kernels"]

[package]
name = "hodu"
version = "0.2.2"
description = "A user-friendly ML framework built in Rust for rapid prototyping and embedded deployment"
license = "BSD-3-Clause"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/hodu-rs/hodu"
documentation = "https://docs.rs/hodu"
readme = "README.md"
keywords = ["tensor", "machine-learning", "hodu"]
categories = ["science"]

[workspace.dependencies]
bincode = "2.0.1"
dashmap = "6.1.0"
flate2 = "1.1.2"
float8 = { version = "0.4.2", default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
half = { version = "2.7.1", default-features = false, features = [
    "num-traits",
    "rand_distr",
] }
hodu_core = { path = "crates/hodu_core", version = "0.2.2" }
hodu_cpu_kernels = { path = "crates/hodu_cpu_kernels", version = "0.2.2" }
hodu_cuda_kernels = { path = "crates/hodu_cuda_kernels", version = "0.2.2" }
hodu_macro_utils = { path = "crates/hodu_macro_utils", version = "0.2.2" }
hodu_metal_kernels = { path = "crates/hodu_metal_kernels", version = "0.2.2" }
hodu_nn = { path = "crates/hodu_nn", version = "0.2.2" }
hodu_nn_macros = { path = "crates/hodu_nn/macros", version = "0.2.2" }
hodu_utils = { path = "crates/hodu_utils", version = "0.2.2" }
hodu_utils_macros = { path = "crates/hodu_utils/macros", version = "0.2.2" }
hodu_xla = "0.4.7"
num-traits = { version = "0.2.19", default-features = false }
paste = "1.0.15"
proc-macro2 = "1.0"
quote = "1.0"
rand = { version = "0.9.2", default-features = false }
rand_distr = { version = "0.5.1", default-features = false }
rayon = "1.11"
serde = { version = "1.0.219", default-features = false, features = [
    "derive",
    "alloc",
] }
spin = "0.10"
syn = { version = "2.0", features = ["full"] }
toml_edit = { version = "0.23.6", default-features = false, features = [
    "parse",
] }

[features]
default = ["std", "serde", "rayon"]
std = ["hodu_internal/std"]
serde = ["hodu_internal/serde"]
rayon = ["std", "hodu_internal/rayon"]

f8e5m2 = ["hodu_internal/f8e5m2"]
f64 = ["hodu_internal/f64"]
u16 = ["hodu_internal/u16"]
u64 = ["hodu_internal/u64"]
i16 = ["hodu_internal/i16"]
i64 = ["hodu_internal/i64"]

cuda = ["hodu_internal/cuda"]
metal = ["std", "hodu_internal/metal"]

xla = ["std", "hodu_internal/xla"]

[dependencies]
hodu_internal = { path = "crates/hodu_internal", version = "0.2.2" }
