[package]
name = "hodu-cli"
version = "0.3.0"
description = "Command-line interface for Hodu ML framework"
license = "BSD-3-Clause"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/daminstudio/hodu"

[[bin]]
name = "hodu"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive"] }
dirs = { workspace = true }
hodu-cli-plugin-sdk = { path = "../hodu-cli-plugin-sdk", version = "0.3.0" }
libloading = { workspace = true }
serde = { workspace = true, features = ["std"] }
serde_json = { workspace = true, features = ["std"] }
