[package]
name = "aa"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[build-dependencies]
hodu_plugin_sdk = "0.3"

[dependencies]
hodu_plugin_sdk = "0.3"

# For backend plugins that need CPU kernels:
# hodu_cpu_kernels = "0.2"
