[package]
name = "hodu_utils_macros"
version = "0.2.2"
description = "hodu utils macros"
license = "BSD-3-Clause"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/hodu-rs/hodu"

[lib]
proc-macro = true

[features]
std = []
serde = []

[dependencies]
hodu_macro_utils = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
