[package]
name = "hodu_script"
version = "0.2.4"
description = "hodu script"
license = "BSD-3-Clause"
authors = ["Han Damin <miniex@daminstudio.net>"]
edition = "2021"
publish = true
repository = "https://github.com/hodu-rs/hodu"

[features]

[dependencies]
